services:
  fedora:
    build:
      context: .
      dockerfile: Containerfile
    container_name: fedora
    restart: unless-stopped
    stdin_open: true
    tty: true
    shm_size: "1gb"

    volumes:
      - fedora_home:/root:Z

volumes:
  fedora_home:
